
name: Проверка кода
run-name: ${{ github.actor }} проверка кода
on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/checkout@v2
        with:
          python-version: 3.10.6
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Flake8
        run: poetry run flake8 .

